import { config } from "@repo/eslint-config/react";

export default [
  ...config,
  {
    ignores: [
      // Generated by the TanStack Router plugin.
      "src/routeTree.gen.ts",
      ".output/**",
      ".nitro/**",
      ".tanstack/**",
    ],
  },
];
