/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppDealsIndexRouteImport } from './routes/_app/deals/index'
import { Route as AppFeedbackIndexRouteImport } from './routes/_app/feedback/index'
import { Route as AppNextStepsIndexRouteImport } from './routes/_app/next-steps/index'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as AppCompaniesCompanyIdIndexRouteImport } from './routes/_app/companies/$companyId/index'
import { Route as AppPeoplePersonIdIndexRouteImport } from './routes/_app/people/$personId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedbackIndexRoute = AppFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNextStepsIndexRoute = AppNextStepsIndexRouteImport.update({
  id: '/next-steps/',
  path: '/next-steps/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesCompanyIdIndexRoute =
  AppCompaniesCompanyIdIndexRouteImport.update({
    id: '/companies/$companyId/',
    path: '/companies/$companyId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPeoplePersonIdIndexRoute = AppPeoplePersonIdIndexRouteImport.update({
  id: '/people/$personId/',
  path: '/people/$personId/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/feedback/': typeof AppFeedbackIndexRoute
  '/next-steps/': typeof AppNextStepsIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/companies/$companyId/': typeof AppCompaniesCompanyIdIndexRoute
  '/people/$personId/': typeof AppPeoplePersonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/feedback': typeof AppFeedbackIndexRoute
  '/next-steps': typeof AppNextStepsIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdIndexRoute
  '/people/$personId': typeof AppPeoplePersonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/feedback/': typeof AppFeedbackIndexRoute
  '/_app/next-steps/': typeof AppNextStepsIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/companies/$companyId/': typeof AppCompaniesCompanyIdIndexRoute
  '/_app/people/$personId/': typeof AppPeoplePersonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/trpc/$'
    | '/companies/'
    | '/deals/'
    | '/feedback/'
    | '/next-steps/'
    | '/people/'
    | '/settings/'
    | '/companies/$companyId/'
    | '/people/$personId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/trpc/$'
    | '/companies'
    | '/deals'
    | '/feedback'
    | '/next-steps'
    | '/people'
    | '/settings'
    | '/companies/$companyId'
    | '/people/$personId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/api/trpc/$'
    | '/_app/companies/'
    | '/_app/deals/'
    | '/_app/feedback/'
    | '/_app/next-steps/'
    | '/_app/people/'
    | '/_app/settings/'
    | '/_app/companies/$companyId/'
    | '/_app/people/$personId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/feedback/': {
      id: '/_app/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AppFeedbackIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/next-steps/': {
      id: '/_app/next-steps/'
      path: '/next-steps'
      fullPath: '/next-steps/'
      preLoaderRoute: typeof AppNextStepsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/companies/$companyId/': {
      id: '/_app/companies/$companyId/'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof AppCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/$personId/': {
      id: '/_app/people/$personId/'
      path: '/people/$personId'
      fullPath: '/people/$personId/'
      preLoaderRoute: typeof AppPeoplePersonIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
  AppFeedbackIndexRoute: typeof AppFeedbackIndexRoute
  AppNextStepsIndexRoute: typeof AppNextStepsIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppCompaniesCompanyIdIndexRoute: typeof AppCompaniesCompanyIdIndexRoute
  AppPeoplePersonIdIndexRoute: typeof AppPeoplePersonIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
  AppFeedbackIndexRoute: AppFeedbackIndexRoute,
  AppNextStepsIndexRoute: AppNextStepsIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppCompaniesCompanyIdIndexRoute: AppCompaniesCompanyIdIndexRoute,
  AppPeoplePersonIdIndexRoute: AppPeoplePersonIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
